// External imports
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class SystemConfigurationService {
  // configuration for phone country code
  countryDetails: any = [{ 'countryCode': 'us', 'dialCode': '(+1)', 'countryName': 'United States' },
  { 'countryCode': 'gb', 'dialCode': '(+44)', 'countryName': 'United Kingdom' },
  { 'countryCode': 'af', 'dialCode': '(+93)', 'countryName': 'Afghanistan' },
  { 'countryCode': 'al', 'dialCode': '(+355)', 'countryName': 'Albania' },
  { 'countryCode': 'dz', 'dialCode': '(+213)', 'countryName': 'Algeria' },
  { 'countryCode': 'as', 'dialCode': '(+1684)', 'countryName': 'American Samoa' },
  { 'countryCode': 'ad', 'dialCode': '(+376)', 'countryName': 'Andorra' },
  { 'countryCode': 'ao', 'dialCode': '(+244)', 'countryName': 'Angola' },
  { 'countryCode': 'ai', 'dialCode': '(+1264)', 'countryName': 'Anguilla' },
  { 'countryCode': 'ag', 'dialCode': '(+1268)', 'countryName': 'Antigua and Barbuda' },
  { 'countryCode': 'ar', 'dialCode': '(+54)', 'countryName': 'Argentina' },
  { 'countryCode': 'am', 'dialCode': '(+374)', 'countryName': 'Armenia' },
  { 'countryCode': 'aw', 'dialCode': '(+297)', 'countryName': 'Aruba' },
  { 'countryCode': 'au', 'dialCode': '(+61)', 'countryName': 'Australia' },
  { 'countryCode': 'at', 'dialCode': '(+43)', 'countryName': 'Austria (Österreich)' },
  { 'countryCode': 'az', 'dialCode': '(+994)', 'countryName': 'Azerbaijan (Azərbaycan)' },
  { 'countryCode': 'bs', 'dialCode': '(+1242)', 'countryName': 'Bahamas' },
  { 'countryCode': 'bh', 'dialCode': '(+973)', 'countryName': 'Bahrain' },
  { 'countryCode': 'bd', 'dialCode': '(+880)', 'countryName': 'Bangladesh' },
  { 'countryCode': 'bb', 'dialCode': '(+1246)', 'countryName': 'Barbados' },
  { 'countryCode': 'by', 'dialCode': '(+375)', 'countryName': 'Belarus' },
  { 'countryCode': 'be', 'dialCode': '(+32)', 'countryName': 'Belgium' },
  { 'countryCode': 'bz', 'dialCode': '(+501)', 'countryName': 'Belize' },
  { 'countryCode': 'bj', 'dialCode': '(+229)', 'countryName': 'Benin' },
  { 'countryCode': 'bm', 'dialCode': '(+1441)', 'countryName': 'Bermuda' },
  { 'countryCode': 'bt', 'dialCode': '(+975)', 'countryName': 'Bhutan' },
  { 'countryCode': 'bo', 'dialCode': '(+591)', 'countryName': 'Bolivia' },
  { 'countryCode': 'ba', 'dialCode': '(+387)', 'countryName': 'Bosnia and Herzegovina' },
  { 'countryCode': 'bw', 'dialCode': '(+267)', 'countryName': 'Botswana' },
  { 'countryCode': 'br', 'dialCode': '(+55)', 'countryName': 'Brazil' },
  { 'countryCode': 'io', 'dialCode': '(+246)', 'countryName': 'British Indian Ocean Territory' },
  { 'countryCode': 'vg', 'dialCode': '(+1284)', 'countryName': 'British Virgin Islands' },
  { 'countryCode': 'bn', 'dialCode': '(+673)', 'countryName': 'Brunei' },
  { 'countryCode': 'bg', 'dialCode': '(+359)', 'countryName': 'Bulgaria' },
  { 'countryCode': 'bf', 'dialCode': '(+226)', 'countryName': 'Burkina Faso' },
  { 'countryCode': 'bi', 'dialCode': '(+257)', 'countryName': 'Burundi' },
  { 'countryCode': 'kh', 'dialCode': '(+855)', 'countryName': 'Cambodia' },
  { 'countryCode': 'cm', 'dialCode': '(+237)', 'countryName': 'Cameroon' },
  { 'countryCode': 'ca', 'dialCode': '(+1)', 'countryName': 'Canada' },
  { 'countryCode': 'cv', 'dialCode': '(+238)', 'countryName': 'Cape Verde' },
  { 'countryCode': 'bq', 'dialCode': '(+599)', 'countryName': 'Caribbean Netherlands' },
  { 'countryCode': 'ky', 'dialCode': '(+1345)', 'countryName': 'Cayman Islands' },
  { 'countryCode': 'cf', 'dialCode': '(+236)', 'countryName': 'Central African Republic' },
  { 'countryCode': 'td', 'dialCode': '(+235)', 'countryName': 'Chad' },
  { 'countryCode': 'cl', 'dialCode': '(+56)', 'countryName': 'Chile' },
  { 'countryCode': 'cn', 'dialCode': '(+86)', 'countryName': 'China' },
  { 'countryCode': 'co', 'dialCode': '(+57)', 'countryName': 'Colombia' },
  { 'countryCode': 'km', 'dialCode': '(+269)', 'countryName': 'Comoros' },
  { 'countryCode': 'cd', 'dialCode': '(+243)', 'countryName': 'Congo (DRC)' },
  { 'countryCode': 'cg', 'dialCode': '(+242)', 'countryName': 'Congo (Republic)' },
  { 'countryCode': 'ck', 'dialCode': '(+682)', 'countryName': 'Cook Islands' },
  { 'countryCode': 'cr', 'dialCode': '(+506)', 'countryName': 'Costa Rica' },
  { 'countryCode': 'ci', 'dialCode': '(+225)', 'countryName': 'Côte d’Ivoire' },
  { 'countryCode': 'hr', 'dialCode': '(+385)', 'countryName': 'Croatia (Hrvatska)' },
  { 'countryCode': 'cu', 'dialCode': '(+53)', 'countryName': 'Cuba' },
  { 'countryCode': 'cw', 'dialCode': '(+599)', 'countryName': 'Curaçao' },
  { 'countryCode': 'cy', 'dialCode': '(+357)', 'countryName': 'Cyprus' },
  { 'countryCode': 'cz', 'dialCode': '(+420)', 'countryName': 'Czech Republic' },
  { 'countryCode': 'dk', 'dialCode': '(+45)', 'countryName': 'Denmark' },
  { 'countryCode': 'dj', 'dialCode': '(+253)', 'countryName': 'Djibouti' },
  { 'countryCode': 'dm', 'dialCode': '(+1767)', 'countryName': 'Dominica' },
  { 'countryCode': 'do', 'dialCode': '(+1)', 'countryName': 'Dominican Republic' },
  { 'countryCode': 'ec', 'dialCode': '(+593)', 'countryName': 'Ecuador' },
  { 'countryCode': 'eg', 'dialCode': '(+20)', 'countryName': 'Egypt' },
  { 'countryCode': 'sv', 'dialCode': '(+503)', 'countryName': 'El Salvador' },
  { 'countryCode': 'gq', 'dialCode': '(+240)', 'countryName': 'Equatorial Guinea' },
  { 'countryCode': 'er', 'dialCode': '(+291)', 'countryName': 'Eritrea' },
  { 'countryCode': 'ee', 'dialCode': '(+372)', 'countryName': 'Estonia' },
  { 'countryCode': 'et', 'dialCode': '(+251)', 'countryName': 'Ethiopia' },
  { 'countryCode': 'fk', 'dialCode': '(+500)', 'countryName': 'Falkland Islands' },
  { 'countryCode': 'fo', 'dialCode': '(+298)', 'countryName': 'Faroe Islands' },
  { 'countryCode': 'fj', 'dialCode': '(+679)', 'countryName': 'Fiji' },
  { 'countryCode': 'fi', 'dialCode': '(+358)', 'countryName': 'Finland' },
  { 'countryCode': 'fr', 'dialCode': '(+33)', 'countryName': 'France' },
  { 'countryCode': 'gf', 'dialCode': '(+594)', 'countryName': 'French Guiana' },
  { 'countryCode': 'pf', 'dialCode': '(+689)', 'countryName': 'French Polynesia' },
  { 'countryCode': 'ga', 'dialCode': '(+241)', 'countryName': 'Gabon' },
  { 'countryCode': 'gm', 'dialCode': '(+220)', 'countryName': 'Gambia' },
  { 'countryCode': 'ge', 'dialCode': '(+995)', 'countryName': 'Georgia' },
  { 'countryCode': 'de', 'dialCode': '(+49)', 'countryName': 'Germany' },
  { 'countryCode': 'gh', 'dialCode': '(+233)', 'countryName': 'Ghana' },
  { 'countryCode': 'gi', 'dialCode': '(+350)', 'countryName': 'Gibraltar' },
  { 'countryCode': 'gr', 'dialCode': '(+30)', 'countryName': 'Greece' },
  { 'countryCode': 'gl', 'dialCode': '(+299)', 'countryName': 'Greenland' },
  { 'countryCode': 'gd', 'dialCode': '(+1473)', 'countryName': 'Grenada' },
  { 'countryCode': 'gp', 'dialCode': '(+590)', 'countryName': 'Guadeloupe' },
  { 'countryCode': 'gu', 'dialCode': '(+1671)', 'countryName': 'Guam' },
  { 'countryCode': 'gt', 'dialCode': '(+502)', 'countryName': 'Guatemala' },
  { 'countryCode': 'gn', 'dialCode': '(+224)', 'countryName': 'Guinea' },
  { 'countryCode': 'gw', 'dialCode': '(+245)', 'countryName': 'Guinea-Bissau' },
  { 'countryCode': 'gy', 'dialCode': '(+592)', 'countryName': 'Guyana' },
  { 'countryCode': 'ht', 'dialCode': '(+509)', 'countryName': 'Haiti' },
  { 'countryCode': 'hn', 'dialCode': '(+504)', 'countryName': 'Honduras' },
  { 'countryCode': 'hk', 'dialCode': '(+852)', 'countryName': 'Hong Kong' },
  { 'countryCode': 'hu', 'dialCode': '(+36)', 'countryName': 'Hungary' },
  { 'countryCode': 'is', 'dialCode': '(+354)', 'countryName': 'Iceland' },
  { 'countryCode': 'in', 'dialCode': '(+91)', 'countryName': 'India' },
  { 'countryCode': 'id', 'dialCode': '(+62)', 'countryName': 'Indonesia' },
  { 'countryCode': 'ir', 'dialCode': '(+98)', 'countryName': 'Iran' },
  { 'countryCode': 'iq', 'dialCode': '(+964)', 'countryName': 'Iraq' },
  { 'countryCode': 'ie', 'dialCode': '(+353)', 'countryName': 'Ireland' },
  { 'countryCode': 'il', 'dialCode': '(+972)', 'countryName': 'Israel' },
  { 'countryCode': 'it', 'dialCode': '(+39)', 'countryName': 'Italy' },
  { 'countryCode': 'jm', 'dialCode': '(+1876)', 'countryName': 'Jamaica' },
  { 'countryCode': 'jp', 'dialCode': '(+81)', 'countryName': 'Japan' },
  { 'countryCode': 'jo', 'dialCode': '(+962)', 'countryName': 'Jordan' },
  { 'countryCode': 'kz', 'dialCode': '(+7)', 'countryName': 'Kazakhstan' },
  { 'countryCode': 'ke', 'dialCode': '(+254)', 'countryName': 'Kenya' },
  { 'countryCode': 'ki', 'dialCode': '(+686)', 'countryName': 'Kiribati' },
  { 'countryCode': 'kw', 'dialCode': '(+965)', 'countryName': 'Kuwait' },
  { 'countryCode': 'kg', 'dialCode': '(+996)', 'countryName': 'Kyrgyzstan' },
  { 'countryCode': 'la', 'dialCode': '(+856)', 'countryName': 'Laos' },
  { 'countryCode': 'lv', 'dialCode': '(+371)', 'countryName': 'Latvia' },
  { 'countryCode': 'lb', 'dialCode': '(+961)', 'countryName': 'Lebanon' },
  { 'countryCode': 'ls', 'dialCode': '(+266)', 'countryName': 'Lesotho' },
  { 'countryCode': 'lr', 'dialCode': '(+231)', 'countryName': 'Liberia' },
  { 'countryCode': 'ly', 'dialCode': '(+218)', 'countryName': 'Libya' },
  { 'countryCode': 'li', 'dialCode': '(+423)', 'countryName': 'Liechtenstein' },
  { 'countryCode': 'lt', 'dialCode': '(+370)', 'countryName': 'Lithuania' },
  { 'countryCode': 'lu', 'dialCode': '(+352)', 'countryName': 'Luxembourg' },
  { 'countryCode': 'mo', 'dialCode': '(+853)', 'countryName': 'Macau' },
  { 'countryCode': 'mk', 'dialCode': '(+389)', 'countryName': 'Macedonia (FYROM)' },
  { 'countryCode': 'mg', 'dialCode': '(+261)', 'countryName': 'Madagascar' },
  { 'countryCode': 'mw', 'dialCode': '(+265)', 'countryName': 'Malawi' },
  { 'countryCode': 'my', 'dialCode': '(+60)', 'countryName': 'Malaysia' },
  { 'countryCode': 'mv', 'dialCode': '(+960)', 'countryName': 'Maldives' },
  { 'countryCode': 'ml', 'dialCode': '(+223)', 'countryName': 'Mali' },
  { 'countryCode': 'mt', 'dialCode': '(+356)', 'countryName': 'Malta' },
  { 'countryCode': 'mh', 'dialCode': '(+692)', 'countryName': 'Marshall Islands' },
  { 'countryCode': 'mq', 'dialCode': '(+596)', 'countryName': 'Martinique' },
  { 'countryCode': 'mr', 'dialCode': '(+222)', 'countryName': 'Mauritania' },
  { 'countryCode': 'mu', 'dialCode': '(+230)', 'countryName': 'Mauritius' },
  { 'countryCode': 'mx', 'dialCode': '(+52)', 'countryName': 'Mexico' },
  { 'countryCode': 'fm', 'dialCode': '(+691)', 'countryName': 'Micronesia' },
  { 'countryCode': 'md', 'dialCode': '(+373)', 'countryName': 'Moldova' },
  { 'countryCode': 'mc', 'dialCode': '(+377)', 'countryName': 'Monaco' },
  { 'countryCode': 'mn', 'dialCode': '(+976)', 'countryName': 'Mongolia' },
  { 'countryCode': 'me', 'dialCode': '(+382)', 'countryName': 'Montenegro' },
  { 'countryCode': 'ms', 'dialCode': '(+1664)', 'countryName': 'Montserrat' },
  { 'countryCode': 'ma', 'dialCode': '(+212)', 'countryName': 'Morocco' },
  { 'countryCode': 'mz', 'dialCode': '(+258)', 'countryName': 'Mozambique' },
  { 'countryCode': 'mm', 'dialCode': '(+95)', 'countryName': 'Myanmar' },
  { 'countryCode': 'na', 'dialCode': '(+264)', 'countryName': 'Namibia' },
  { 'countryCode': 'nr', 'dialCode': '(+674)', 'countryName': 'Nauru' },
  { 'countryCode': 'np', 'dialCode': '(+977)', 'countryName': 'Nepal' },
  { 'countryCode': 'nl', 'dialCode': '(+31)', 'countryName': 'Netherlands' },
  { 'countryCode': 'nc', 'dialCode': '(+687)', 'countryName': 'New Caledonia' },
  { 'countryCode': 'nz', 'dialCode': '(+64)', 'countryName': 'New Zealand' },
  { 'countryCode': 'ni', 'dialCode': '(+505)', 'countryName': 'Nicaragua' },
  { 'countryCode': 'ne', 'dialCode': '(+227)', 'countryName': 'Niger' },
  { 'countryCode': 'ng', 'dialCode': '(+234)', 'countryName': 'Nigeria' },
  { 'countryCode': 'nu', 'dialCode': '(+683)', 'countryName': 'Niue' },
  { 'countryCode': 'nf', 'dialCode': '(+672)', 'countryName': 'Norfolk Island' },
  { 'countryCode': 'kp', 'dialCode': '(+850)', 'countryName': 'North Korea' },
  { 'countryCode': 'mp', 'dialCode': '(+1670)', 'countryName': 'Northern Mariana Islands' },
  { 'countryCode': 'no', 'dialCode': '(+47)', 'countryName': 'Norway' },
  { 'countryCode': 'om', 'dialCode': '(+968)', 'countryName': 'Oman' },
  { 'countryCode': 'pk', 'dialCode': '(+92)', 'countryName': 'Pakistan' },
  { 'countryCode': 'pw', 'dialCode': '(+680)', 'countryName': 'Palau' },
  { 'countryCode': 'ps', 'dialCode': '(+970)', 'countryName': 'Palestine' },
  { 'countryCode': 'pa', 'dialCode': '(+507)', 'countryName': 'Panama' },
  { 'countryCode': 'pg', 'dialCode': '(+675)', 'countryName': 'Papua New Guinea' },
  { 'countryCode': 'py', 'dialCode': '(+595)', 'countryName': 'Paraguay' },
  { 'countryCode': 'pe', 'dialCode': '(+51)', 'countryName': 'Peru' },
  { 'countryCode': 'ph', 'dialCode': '(+63)', 'countryName': 'Philippines' },
  { 'countryCode': 'pl', 'dialCode': '(+48)', 'countryName': 'Poland' },
  { 'countryCode': 'pt', 'dialCode': '(+351)', 'countryName': 'Portugal' },
  { 'countryCode': 'pr', 'dialCode': '(+974)', 'countryName': 'Puerto Rico' },
  { 'countryCode': 'qa', 'dialCode': '(+974)', 'countryName': 'Qatar' },
  { 'countryCode': 're', 'dialCode': '(+262)', 'countryName': 'Réunion' },
  { 'countryCode': 'ro', 'dialCode': '(+40)', 'countryName': 'Romania' },
  { 'countryCode': 'ru', 'dialCode': '(+7)', 'countryName': 'Russia' },
  { 'countryCode': 'rw', 'dialCode': '(+250)', 'countryName': 'Rwanda' },
  { 'countryCode': 'bl', 'dialCode': '(+590)', 'countryName': 'Saint Barthélemy' },
  { 'countryCode': 'sh', 'dialCode': '(+290)', 'countryName': 'Saint Helena' },
  { 'countryCode': 'kn', 'dialCode': '(+1869)', 'countryName': 'Saint Kitts and Nevis' },
  { 'countryCode': 'lc', 'dialCode': '(+1758)', 'countryName': 'Saint Lucia' },
  { 'countryCode': 'mf', 'dialCode': '(+590)', 'countryName': 'Saint Martin' },
  { 'countryCode': 'pm', 'dialCode': '(+508)', 'countryName': 'Saint Pierre and Miquelon' },
  { 'countryCode': 'vc', 'dialCode': '(+1784)', 'countryName': 'Saint Vincent and the Grenadines' },
  { 'countryCode': 'ws', 'dialCode': '(+685)', 'countryName': 'Samoa' },
  { 'countryCode': 'sm', 'dialCode': '(+378)', 'countryName': 'San Marino' },
  { 'countryCode': 'st', 'dialCode': '(+239)', 'countryName': 'São Tomé and Príncipe' },
  { 'countryCode': 'sa', 'dialCode': '(+966)', 'countryName': 'Saudi Arabia' },
  { 'countryCode': 'sn', 'dialCode': '(+221)', 'countryName': 'Senegal' },
  { 'countryCode': 'rs', 'dialCode': '(+381)', 'countryName': 'Serbia' },
  { 'countryCode': 'sc', 'dialCode': '(+248)', 'countryName': 'Seychelles' },
  { 'countryCode': 'sl', 'dialCode': '(+232)', 'countryName': 'Sierra Leone' },
  { 'countryCode': 'sg', 'dialCode': '(+65)', 'countryName': 'Singapore' },
  { 'countryCode': 'sx', 'dialCode': '(+1721)', 'countryName': 'Sint Maarten' },
  { 'countryCode': 'sk', 'dialCode': '(+421)', 'countryName': 'Slovakia' },
  { 'countryCode': 'si', 'dialCode': '(+386)', 'countryName': 'Slovenia' },
  { 'countryCode': 'sb', 'dialCode': '(+677)', 'countryName': 'Solomon Islands' },
  { 'countryCode': 'so', 'dialCode': '(+252)', 'countryName': 'Somalia' },
  { 'countryCode': 'za', 'dialCode': '(+27)', 'countryName': 'South Africa' },
  { 'countryCode': 'kr', 'dialCode': '(+82)', 'countryName': 'South Korea' },
  { 'countryCode': 'ss', 'dialCode': '(+211)', 'countryName': 'South Sudan' },
  { 'countryCode': 'es', 'dialCode': '(+34)', 'countryName': 'Spain' },
  { 'countryCode': 'lk', 'dialCode': '(+94)', 'countryName': 'Sri Lanka' },
  { 'countryCode': 'sd', 'dialCode': '(+249)', 'countryName': 'Sudan' },
  { 'countryCode': 'sr', 'dialCode': '(+597)', 'countryName': 'Suriname' },
  { 'countryCode': 'sz', 'dialCode': '(+268)', 'countryName': 'Swaziland' },
  { 'countryCode': 'se', 'dialCode': '(+46)', 'countryName': 'Sweden' },
  { 'countryCode': 'ch', 'dialCode': '(+41)', 'countryName': 'Switzerland' },
  { 'countryCode': 'sy', 'dialCode': '(+963)', 'countryName': 'Syria' },
  { 'countryCode': 'tw', 'dialCode': '(+886)', 'countryName': 'Taiwan' },
  { 'countryCode': 'tj', 'dialCode': '(+992)', 'countryName': 'Tajikistan' },
  { 'countryCode': 'tz', 'dialCode': '(+255)', 'countryName': 'Tanzania' },
  { 'countryCode': 'th', 'dialCode': '(+66)', 'countryName': 'Thailand' },
  { 'countryCode': 'tl', 'dialCode': '(+670)', 'countryName': 'Timor-Leste' },
  { 'countryCode': 'tg', 'dialCode': '(+228)', 'countryName': 'Togo' },
  { 'countryCode': 'tk', 'dialCode': '(+690)', 'countryName': 'Tokelau' },
  { 'countryCode': 'to', 'dialCode': '(+676)', 'countryName': 'Tonga' },
  { 'countryCode': 'tt', 'dialCode': '(+1868)', 'countryName': 'Trinidad and Tobago' },
  { 'countryCode': 'tn', 'dialCode': '(+216)', 'countryName': 'Tunisia' },
  { 'countryCode': 'tr', 'dialCode': '(+90)', 'countryName': 'Turkey' },
  { 'countryCode': 'tm', 'dialCode': '(+993)', 'countryName': 'Turkmenistan' },
  { 'countryCode': 'tc', 'dialCode': '(+1649)', 'countryName': 'Turks and Caicos Islands' },
  { 'countryCode': 'tv', 'dialCode': '(+688)', 'countryName': 'Tuvalu' },
  { 'countryCode': 'vi', 'dialCode': '(+1340)', 'countryName': 'U.S. Virgin Islands' },
  { 'countryCode': 'ug', 'dialCode': '(+256)', 'countryName': 'Uganda' },
  { 'countryCode': 'ua', 'dialCode': '(+380)', 'countryName': 'Ukraine' },
  { 'countryCode': 'ae', 'dialCode': '(+971)', 'countryName': 'United Arab Emirates' },
  { 'countryCode': 'gb', 'dialCode': '(+44)', 'countryName': 'United Kingdom' },
  { 'countryCode': 'us', 'dialCode': '(+1)', 'countryName': 'United States' },
  { 'countryCode': 'uy', 'dialCode': '(+598)', 'countryName': 'Uruguay' },
  { 'countryCode': 'uz', 'dialCode': '(+998)', 'countryName': 'Uzbekistan' },
  { 'countryCode': 'vu', 'dialCode': '(+678)', 'countryName': 'Vanuatu' },
  { 'countryCode': 'va', 'dialCode': '(+39)', 'countryName': 'Vatican City' },
  { 'countryCode': 've', 'dialCode': '(+58)', 'countryName': 'Venezuela' },
  { 'countryCode': 'vn', 'dialCode': '(+84)', 'countryName': 'Vietnam' },
  { 'countryCode': 'wf', 'dialCode': '(+681)', 'countryName': 'Wallis and Futuna' },
  { 'countryCode': 'ye', 'dialCode': '(+967)', 'countryName': 'Yemen' },
  { 'countryCode': 'zm', 'dialCode': '(+260)', 'countryName': 'Zambia' },
  { 'countryCode': 'zw', 'dialCode': '(+263)', 'countryName': 'Zimbabwe' }
  ];
  private yearsList: any = [{ id: '2014', name: '2014' }, { id: '2015', name: '2015' }, { id: '2016', name: '2016' }, { id: '2017', name: '2017' }, { id: '2018', name: '2018' }, { id: '2019', name: '2019' },{ id: '2020', name: '2020' }];
  private monthList: any = [
    { id: '01', name: 'Jan' },
    { id: '02', name: 'Feb' },
    { id: '03', name: 'Mar' },
    { id: '04', name: 'Apr' },
    { id: '05', name: 'May' },
    { id: '06', name: 'Jun' },
    { id: '07', name: 'Jul' },
    { id: '08', name: 'Aug' },
    { id: '09', name: 'Sep' },
    { id: '10', name: 'Oct' },
    { id: '11', name: 'Nov' },
    { id: '12', name: 'Dec' }
  ];

  constructor() { }

  public getCountryDetail(): any {
    return this.countryDetails;
  };

  public getYearList() {
    return this.yearsList;
  }

  public getMonthList() {
    return this.monthList;
  }

  public agGridCaseInSensitiveSort(valueA, valueB) {
    if ((valueA === null && valueB === null) || (valueA === undefined && valueB === undefined)) {
      return 0;
    }

    if (valueA === null || valueA === undefined) {
      return -1;
    }
    if (valueB === null || valueB === undefined) {
      return 1;
    }

    let upperValueA = valueA.toUpperCase();
    let upperValueB = valueB.toUpperCase();
    return upperValueA === upperValueB ? 0 : (upperValueA > upperValueB) ? 1 : -1;
  }

}
